### ISSUE TITLE
Diameter limit exception

### ISSUE THREAD

**Issue by mpmjr7** [shtirlitsDva/Revit-PCF-Exporter#36]
I inadvertently cleared out the value in the diameter limit text box and it resulted in an unhandled exception.
![snag-20170714-0000](https://user-images.githubusercontent.com/10454020/28217031-b839e23a-6881-11e7-97df-045a0c3d9320.png)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Double.Parse(String s)
   at PCF_Exporter.PCF_Exporter_form.textBox22_TextChanged(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnTextChanged(EventArgs e)
   at System.Windows.Forms.TextBoxBase.WmReflectCommand(Message& m)
   at System.Windows.Forms.TextBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by shtirlitsDva** [comment]
Yes, there's no input validation right now for the various input fields, so it is up to the user to get this right.

**Comment by mpmjr7** [comment]
No worries, I was throwing it out there so that you knew about it.
